name: Build & Deploy Dokka Docs

on:
  release:
    types: [ created ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build Project
        run: ./gradlew build

      - name: Build Dokka HTML Docs
        run: ./gradlew dokkaGenerate

      - name: Upload Dokka Docs as Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/dokka

  deploy:
    needs: build-and-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4